/**
 * Phase 5A: GitHub Issue Creation & Verification Service
 * Enables human-approved external action creation of a GitHub issue for NichePulse research reports.
 */

/**
 * Creates a GitHub issue for a verified NichePulse report.
 * Requires GITHUB_TOKEN and GITHUB_REPO (e.g., 'owner/repo').
 */
export async function createGitHubIssue({ goal, report, runId, options = {} }) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;

  if (options.clientOverride) {
    return options.clientOverride.createIssue({ goal, report, runId });
  }

  if (!token || !repo) {
    return {
      success: false,
      status: 'action_unavailable',
      message: 'GitHub integration unavailable: GITHUB_TOKEN or GITHUB_REPO not configured in backend environment',
      issue: null
    };
  }

  const [owner, repoName] = repo.split('/');
  if (!owner || !repoName) {
    return {
      success: false,
      status: 'action_failed',
      message: 'Invalid GITHUB_REPO configuration format. Expected "owner/repo"',
      issue: null
    };
  }

  // Format issue body from report findings and opportunities
  const opportunitiesText = Array.isArray(report?.opportunities) && report.opportunities.length > 0
    ? report.opportunities.map(o => `- **${o.opportunity}**: ${o.rationale || ''}`).join('\n')
    : '- None identified';

  const insightsText = Array.isArray(report?.aiInsights) && report.aiInsights.length > 0
    ? report.aiInsights.map(i => `- **${i.insight}**: ${i.grounding || ''}`).join('\n')
    : '- None identified';

  const sourcesText = Array.isArray(report?.sourceLinks) && report.sourceLinks.length > 0
    ? report.sourceLinks.map(s => `- [${s.title || s.url}](${s.url}) (${s.source})`).join('\n')
    : '- None attached';

  const issueTitle = `[NichePulse Report] Research Opportunities: ${goal}`;
  const issueBody = `## NichePulse Autonomous Research Report
**Research Goal:** ${goal}
**Run ID:** \`${runId}\`
**Generated At:** ${new Date().toISOString()}

---

### Key Opportunities
${opportunitiesText}

### Grounded Insights
${insightsText}

### Verified Sources
${sourcesText}

---
*Generated by NichePulse Autonomous Intelligence Agent*`;

  try {
    const response = await fetch(`https://api.github.com/repos/${owner}/${repoName}/issues`, {
      method: 'POST',
      headers: {
        'Accept': 'application/vnd.github+json',
        'Authorization': `Bearer ${token}`,
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'NichePulse-Agent/1.0',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        title: issueTitle,
        body: issueBody,
        labels: ['nichepulse-report', 'automated-action']
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      return {
        success: false,
        status: 'action_failed',
        message: `GitHub API error (${response.status}): ${errText.slice(0, 300)}`,
        issue: null
      };
    }

    const issueData = await response.json();

    return {
      success: true,
      status: 'action_succeeded',
      message: `GitHub issue #${issueData.number} created successfully`,
      issue: {
        id: issueData.id,
        number: issueData.number,
        url: issueData.html_url,
        title: issueData.title,
        createdAt: issueData.created_at
      }
    };
  } catch (err) {
    return {
      success: false,
      status: 'action_failed',
      message: `Network error creating GitHub issue: ${err.message}`,
      issue: null
    };
  }
}

/**
 * Verifies that a previously created GitHub issue exists on GitHub.
 */
export async function verifyGitHubIssue(issueNumber, options = {}) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;

  if (options.clientOverride) {
    return options.clientOverride.verifyIssue(issueNumber);
  }

  if (!token || !repo) {
    return {
      verified: false,
      status: 'action_failed',
      message: 'GitHub credentials missing for verification',
      details: null
    };
  }

  const [owner, repoName] = repo.split('/');

  try {
    const response = await fetch(`https://api.github.com/repos/${owner}/${repoName}/issues/${issueNumber}`, {
      method: 'GET',
      headers: {
        'Accept': 'application/vnd.github+json',
        'Authorization': `Bearer ${token}`,
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'NichePulse-Agent/1.0'
      }
    });

    if (!response.ok) {
      return {
        verified: false,
        status: 'action_failed',
        message: `Verification check failed with HTTP ${response.status}`,
        details: null
      };
    }

    const issueData = await response.json();

    return {
      verified: true,
      status: 'action_verified',
      message: `Issue #${issueNumber} verified successfully on GitHub`,
      details: {
        number: issueData.number,
        url: issueData.html_url,
        state: issueData.state,
        title: issueData.title
      }
    };
  } catch (err) {
    return {
      verified: false,
      status: 'action_failed',
      message: `Verification error: ${err.message}`,
      details: null
    };
  }
}
